### ISSUE TITLE
Think about negative sample for the split classifiers

### ISSUE THREAD

**Issue by josh-marsh** [MatthewJA/thursday#12]

**Comment by josh-marsh** [comment]
When do you get in today? I have a few questions about exactly what I can request. Is every radio source potentially an FR-1 or an FR-2? Are they all centered? What is the resolution range? etc

**Comment by MatthewJA** [comment]
I'll be in on Thursday or Friday. Every radio source is a candidate. They are centred on the individual radio blobs (not the galaxy!) so you can't assume they're centred in general. The resolutions are the same as the ones you've got.

**Comment by MatthewJA** [comment]
I can give arbitrary sizes of image but let's cap it at, say, 10 arcmin.

**Comment by josh-marsh** [comment]
Stats: 50,000 random radio sources at 10 arcmin. Will almost certainly end up using less, but I no reason to limit it.
