### ISSUE TITLE
Try naïve Bayes + HOG

### ISSUE THREAD

**Issue by josh-marsh** [MatthewJA/thursday#16]

**Comment by MatthewJA** [comment]
Use `sklearn`; run NB on both the raw images and HOG features

**Comment by MatthewJA** [comment]
You can plot your weights with `nb.theta_`

**Comment by josh-marsh** [comment]
These all worked depressingly well. See commit f43bdc7. RFT worked best on both RAW and HOG images, achieving 0.78 and 0.79 respectively. For Naive Bayes, 0.56 and 0.75, and for SVM, 0.60 and 0.78
