### ISSUE TITLE
PHOG

### ISSUE THREAD

**Issue by josh-marsh** [MatthewJA/thursday#17]

**Comment by josh-marsh** [comment]
Just use Scipy HOG for this?

**Comment by MatthewJA** [comment]
`skimage`, yeah

**Comment by josh-marsh** [comment]
It looks like they don't do any block overlap with PHOG. Should I do the same? It seemed to work for them. Unless I have misinterpreted the paper

**Comment by MatthewJA** [comment]
If that's what they do, then do that

**Comment by josh-marsh** [comment]
Well... it turns out you can't define stride in skimage's implementation of hog. I can adapt mine, but it is offensively slow and I don't fully trust that it is working properly. If I do use mine, I will have to show you my implementation first, because I have questions. I'll get started in #18
