### ISSUE TITLE
uncenter then recenter

### ISSUE THREAD

**Issue by josh-marsh** [MatthewJA/thursday#19]
Try Matthew's code

**Comment by josh-marsh** [comment]
Can we discuss this more? Because I foresee a number of issues in reformating the images to be the same size

**Comment by MatthewJA** [comment]
Sure, what issues?

**Comment by josh-marsh** [comment]
Well the size that we can crop the final image to is dictated by the maximum possible distance that the calculated centre can be from the actual centre of the image. So that means if we have anything too far towards the edge in a single image we risk losing parts of the FR-2 sources.  I mean we can dictate the amount of shifting in the image generator, but what about the raw sources? I don't feel like I have a decent enough understdning of the actual data I will be working with in order to make something that can be readily adapted to it.

**Comment by josh-marsh** [comment]
Also are the 200's in `centre= (np.mgrid[:200, :200] * img).mean(axis=0).mean(axis=0)` specific to the dimensions of the image that you were working with? What do they do?

**Comment by josh-marsh** [comment]
Ok figured out the 200 thing, but what is this supposed to return? For an image of size x^2, I'm getting x outputs

**Comment by MatthewJA** [comment]
Check the shape of your images. Should be (200, 200)

**Comment by josh-marsh** [comment]
They are not. In raw form, they are (267, 267). I've rescaled all mine too (89, 89). So I can't just change to (89, 89)?

**Comment by MatthewJA** [comment]
Oh, sure. But there should be exactly two axes.

**Comment by josh-marsh** [comment]
'train_centers =  []

for i in range(train_x.shape[0]):
    centre = (np.mgrid[:89, :89] * train_x[i, :, :]).mean(axis=0).mean(axis=0)
    train_centers.append(centre) 
    
np.asarray(train_centers).shape'


output:
(123, 89)

where train_x.shape[0] = 123

**Comment by MatthewJA** [comment]
Ah, might have got the means wrong. Check the shape of the product and fix
accordingly.

**Comment by josh-marsh** [comment]
So get rid of the second mean(axis=0)? That gets the right shape. Dare I ask what the shape of the product is supposed to be?
