### ISSUE TITLE
Write a way to evaluate rule

### ISSUE THREAD

**Issue by josh-marsh** [MatthewJA/thursday#2]
Depends on #1

**Comment by josh-marsh** [comment]
Define a metric to evaluate rule

**Comment by MatthewJA** [comment]
e.g. precision/recall, f1 score, accuracy, balanced accuracy, confusion matrix

**Comment by MatthewJA** [comment]
Evaluate my extremely great classifier using your evaluation method:

```python
def classify(image):
  """Given an image of a radio source, determines the probability it is an FR-II.

  Parameters
  -----------
  image : numpy.ndarray
    The image to classify.

  Returns
  --------
  float
    Probability that the image is an FR-II.
  """
  return 0.0
```

Then evaluate your classifier (i.e. the rule from #1). Post both scores here.

**Comment by josh-marsh** [comment]
Hopefully, this clears up any lingering questions about the prowess of this truly state of the art classifier

Recall: 0.0
Accuracy: 0.6544943820224719
F1 Score: 0.0
Confusion Matrix
[[   0.    0.]
 [ 233.  123.]]

**Comment by MatthewJA** [comment]
Balanced accuracy + precision + recall seems a good way to evaluate these classifiers (noting that existing literature uses precision + recall, and balanced accuracy is pretty good). I think we can consider this resolved!
