### ISSUE TITLE
InceptionResNetV2

### ISSUE THREAD

**Issue by josh-marsh** [MatthewJA/thursday#20]
Well it can run, but I'm going to have to leave it overnight

**Comment by MatthewJA** [comment]
How are you training it?

**Comment by josh-marsh** [comment]
So its weights are pretrained on the imagenet dataset. Basically all I have to do it to retrain the first few and last few layers to adapt them to the new classes and input dimensions. Their weights are the ones that have to be retrained the most. Then I let all the weights become trainable, but i'm pretty sure they don't need to adjust much.

**Comment by josh-marsh** [comment]
It's like two hours per epoch

**Comment by josh-marsh** [comment]
But in one epoch it's gone from 0.5 to 0.6  balanced accuracy on the uncentered images, so it's relatively fast on a per epoch basis.

**Comment by josh-marsh** [comment]
So this crashed overnight on the end of the second epoch for some reason...

**Comment by josh-marsh** [comment]
See commit  884b816 for code

**Comment by josh-marsh** [comment]
No longer applicable. VGG was used instead
