### ISSUE TITLE
Write up logistic regression

### ISSUE THREAD

**Issue by josh-marsh** [MatthewJA/thursday#3]
Only try after #1 and #2 are complete 
Maybe use rotations?

**Comment by MatthewJA** [comment]
Bishop+06 4.3.2 discusses logistic regression. You could also look at [my thesis](https://github.com/chengsoonong/crowdastro/raw/master/tex/thesis/Alger%20-%202016%20-%20Learning%20from%20Crowd%20Labels%20to%20find%20Black%20Holes.pdf), 3–3.1.2.

**Comment by MatthewJA** [comment]
Write up this logistic regression experiment in your report. Document your experimental design and results. Basically a) communicate your numbers, b) convince me these numbers are meaningful, c) explain what these numbers mean.

**Comment by josh-marsh** [comment]
Ok.  Was I supposed to do a write up in this notebook as well?

**Comment by MatthewJA** [comment]
It's good practice to write notes in the text cells of any Jupyter notebooks you're using (most importantly an introduction and a conclusion, but ideally other text too). The report is the main focus of the "convince me these numbers are meaningful" etc., though.

**Comment by josh-marsh** [comment]
see commit 7b9893fb09708aeaf89dce30964b3a617f044656
