### ISSUE TITLE
Read Ch 4 of Szeliski and HOG

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/thursday#4]
And also read up on HOG, either http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7008017 or https://www2.cs.duke.edu/courses/fall17/compsci527/notes/hog.pdf

**Comment by MatthewJA** [comment]
Revisit Ch4 now you've read the HOG paper. Read the PHOG paper (focus on HOG).

**Comment by josh-marsh** [comment]
That textbook is not exactly 'light' reading. Read it to the best of my extent (with time constraints taken into consideration) as well as the PHOG paper
