### ISSUE TITLE
Run unseen data through logistic regression (keras)

### ISSUE THREAD

**Issue by josh-marsh** [MatthewJA/thursday#8]
To check performance. Use Matthew's fake FR-II as well as sliced off FR-I's.

**Comment by MatthewJA** [comment]
Rescale your inputs!

**Comment by josh-marsh** [comment]
See ac3c66ab39374e5c9c861124bc23d0ba1a56fdfe

**Comment by josh-marsh** [comment]
I can't push anything for some reason. But this is done. Achieved 0.59 acc on the leftover FR-I samples and the ake FR-II was correctly predicted
