### ISSUE TITLE
Run unseen samples through keras logistic regression 

### ISSUE THREAD

**Issue by josh-marsh** [MatthewJA/thursday#9]
To check performance. Use Matthew's fake FR-II as well as sliced off FR-I's.

**Comment by josh-marsh** [comment]
Got 83.6% accuracy on the leftover FR-I's, but couldn't get it working on fr.fits. Probably some error on my part (though I cannot find it). See commit 055be5d

**Comment by MatthewJA** [comment]
Might be a scale issue. Check the mean of the fake FR-II against the means of the real data.
